# Generated by Django 4.2.7 on 2023-12-02 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0004_prestamo_empleado_alter_prestamo_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='empleado',
        ),
    ]
