# Generated by Django 4.2.7 on 2023-12-04 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0008_tipo_cliente_customuser_tipo_cuenta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='tipo_cuenta',
            new_name='tipo_cliente',
        ),
    ]
