# Generated by Django 4.2.7 on 2023-12-09 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0009_rename_tipo_cuenta_customuser_tipo_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='nombre',
            field=models.CharField(default='Hola', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('nro_tarjeta', models.DecimalField(decimal_places=0, max_digits=15, primary_key=True, serialize=False)),
                ('cvv', models.DecimalField(decimal_places=0, max_digits=3)),
                ('banco', models.CharField(max_length=50)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
